spring:
  datasource:
    url: ${MYSQL_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
app:
  admin:
    enabled: ${ADMIN_ENABLED:true}
    account: ${ADMIN_ACCOUNT:admin}
    password: ${ADMIN_PASSWORD}
